ASK_COURSE_REQUIREMENTS = "ASK_COURSE_REQUIREMENTS"
ASK_COURSE_ELIGIBILITY = "ASK_COURSE_ELIGIBILITY"
ASK_REGISTRATION_TIME = "ASK_REGISTRATION_TIME"
ASK_DROP_TIME = "ASK_DROP_TIME"
ASK_REGISTRATION_PLATFORM = "ASK_REGISTRATION_PLATFORM"
ASK_PREREQUISITE_ONLY = "ASK_PREREQUISITE_ONLY"  # Chỉ hỏi về prerequisites (phải pass)
ASK_PREVIOUS_ONLY = "ASK_PREVIOUS_ONLY"  # Chỉ hỏi về previous (chỉ cần đã học)
UNKNOWN = "UNKNOWN"
